### ISSUE TITLE
难题1

### ISSUE THREAD

**Issue by qzren1982** [qzren1982/hello-world#1]
难题1

**Comment by hsyuan** [comment]
哥们儿，你在Orca那边开了个PR？

**Comment by qzren1982** [comment]
@hsyuan 没有，
我感觉pg的所有索引 ，在传统的分页排序要求下的查询性能都不好，不无法避免sort这步，如果不用sort，根据索引的扫描顺序，那么性能不好。oracle也一样，
比如有个查询 
select * from tab t
where t.datecol between ：1 and ：2
and t.namecol like ‘xxx%’
order by datecol desc 
limit 24；

我创建了一个索引： datecol，namecol 的组合索引（b*tree）

1，假设：namecol like ‘xxx%’的数据比较多，那么上面的查询性能是可以的，根据索引的顺序扫描，可能扫描几个不多的块就能找到满足条件的24条第一页的记录

2，假设：namecol like ‘xxx%' 的数据比较少，那么上面的查询性能就不行了，因为要根据索引的顺序，扫描到很多的块才能满足24条记录。

这个情况我看了。pg的gin索引，gist索引都不能满足要求，而且，gin的索引的维护代价高，创建索引耗时长，影响insert的性能。而且还不能消除sort node

头疼，不好解决这个问题啊
